/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_bank;
import tugas_bank.setor;
import tugas_bank.tarik;
import javax.swing.JOptionPane;

/**
 *
 * @author Smktelkom
 */
public class Frame2 extends javax.swing.JFrame {
    String str,str1;
    int choice,z,pin=1234,counter=0,a=3;
    int t,s,tab=50000;

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pilih = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PILIHAN MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 30, 100, 17);

        jLabel2.setText("[1] INFORMASI SALDO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 70, 130, 20);

        jLabel3.setText("[2] PENYETORAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 100, 120, 20);

        jLabel4.setText("[3] PENARIKAN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 130, 90, 14);

        jLabel5.setText("[4] PETUNJUK");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 160, 90, 14);

        jLabel6.setText("[5] KELUAR");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 190, 70, 14);
        getContentPane().add(pilih);
        pilih.setBounds(110, 220, 170, 30);

        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 260, 90, 23);

        jPanel1.setBackground(new java.awt.Color(255, 51, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int Plhn;
        Plhn = Integer.parseInt(pilih.getText().toString());
        
        if (Plhn == 1){
            this.setVisible(true);
            JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " + tab);
            z = JOptionPane.showConfirmDialog(null, "Melanjutkan transaksi lain?","ATM BNI SYARIAH-BOJONEGORO",
                JOptionPane.YES_NO_OPTION, 3);
            if(z==0){
                this.setVisible(true);
            }
                              
            else{
                JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BNI SYARIAH-BOJONEGORO, ambil kartu ATM Anda");
                System.exit(0);
            }
        }
        else if (Plhn == 2){
            this.setVisible(false);
            str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran : ");
            s = Integer.parseInt(str1);
            setor hasil = new setor();
            hasil.menabung(tab, s);
            tab = hasil.getsaldo();
            z = JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI SYARIAH-BOJONEGORO",
                    JOptionPane.YES_NO_OPTION, 3);
            if(z==0){
                this.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Terimakasih telah menggunakan ATM BRI, ambil kartu ATM Anda.");
                System.exit(0);
            }
        }
        else if (Plhn == 3){
            this.setVisible(false);
            str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : ");
            t = Integer.parseInt(str1);
            tarik mengambil = new tarik();
            mengambil.ambil(tab,t);
            tab = mengambil.getsaldo();
            z = JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI SYARIAH-BOJONEGORO",
                    JOptionPane.YES_NO_OPTION, 3);
            if(z==0){
                this.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI, ambil kartu ATM Anda.");   
                System.exit(0);
            }               
        }
        else if (Plhn == 4){
            z = JOptionPane.showConfirmDialog(null,"Cara Penggunaan Aplikasi\n[1] Masukkan PIN dengan benar\n[2] Bertransaksilah dengan benar sesuai pilihan\n[3] Gunakan Uang sesuai kebutuhan dan rajinlah menabung\n ","INFO",
                    JOptionPane.YES_NO_OPTION, 3);
            if(z==0){
                this.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI, ambil kartu ATM Anda");
                System.exit(0);
            }
        }
        else if (Plhn == 5){
            JOptionPane.showMessageDialog(null,"SILAHKAN AMBIL KARTU ATM ANDA","TERIMAKASIH",JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pilih;
    // End of variables declaration//GEN-END:variables
}
